// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type Categoria struct {
	ID          int64
	Nombre      string
	Descripcion string
}

type Producto struct {
	ID          int64
	Nombre      string
	Precio      float64
	Stock       int64
	CategoriaID int64
}
