// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarCategoria = `-- name: ActualizarCategoria :one
UPDATE categorias
SET nombre = ?, descripcion = ?
WHERE id = ?
RETURNING id, nombre, descripcion
`

type ActualizarCategoriaParams struct {
	Nombre      string
	Descripcion string
	ID          int64
}

func (q *Queries) ActualizarCategoria(ctx context.Context, arg ActualizarCategoriaParams) (Categoria, error) {
	row := q.db.QueryRowContext(ctx, actualizarCategoria, arg.Nombre, arg.Descripcion, arg.ID)
	var i Categoria
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const actualizarProducto = `-- name: ActualizarProducto :one
UPDATE productos
SET nombre = ?, precio = ?, stock = ?, categoria_id = ?
WHERE id = ?
RETURNING id, nombre, precio, stock, categoria_id
`

type ActualizarProductoParams struct {
	Nombre      string
	Precio      float64
	Stock       int64
	CategoriaID int64
	ID          int64
}

func (q *Queries) ActualizarProducto(ctx context.Context, arg ActualizarProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, actualizarProducto,
		arg.Nombre,
		arg.Precio,
		arg.Stock,
		arg.CategoriaID,
		arg.ID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Precio,
		&i.Stock,
		&i.CategoriaID,
	)
	return i, err
}

const borrarCategoria = `-- name: BorrarCategoria :execrows
DELETE FROM categorias WHERE id = ?
`

func (q *Queries) BorrarCategoria(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarCategoria, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarProducto = `-- name: BorrarProducto :execrows
DELETE FROM productos WHERE id = ?
`

func (q *Queries) BorrarProducto(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarProducto, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarCategoriaPorID = `-- name: BuscarCategoriaPorID :one
SELECT id, nombre, descripcion FROM categorias
WHERE id = ?
`

func (q *Queries) BuscarCategoriaPorID(ctx context.Context, id int64) (Categoria, error) {
	row := q.db.QueryRowContext(ctx, buscarCategoriaPorID, id)
	var i Categoria
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const buscarProductoPorID = `-- name: BuscarProductoPorID :one
SELECT id, nombre, precio, stock, categoria_id FROM productos
WHERE id = ?
`

func (q *Queries) BuscarProductoPorID(ctx context.Context, id int64) (Producto, error) {
	row := q.db.QueryRowContext(ctx, buscarProductoPorID, id)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Precio,
		&i.Stock,
		&i.CategoriaID,
	)
	return i, err
}

const crearCategoria = `-- name: CrearCategoria :one
INSERT INTO categorias (nombre, descripcion)
VALUES (?, ?)
RETURNING id, nombre, descripcion
`

type CrearCategoriaParams struct {
	Nombre      string
	Descripcion string
}

func (q *Queries) CrearCategoria(ctx context.Context, arg CrearCategoriaParams) (Categoria, error) {
	row := q.db.QueryRowContext(ctx, crearCategoria, arg.Nombre, arg.Descripcion)
	var i Categoria
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const crearProducto = `-- name: CrearProducto :one
INSERT INTO productos (nombre, precio, stock, categoria_id)
VALUES (?, ?, ?, ?)
RETURNING id, nombre, precio, stock, categoria_id
`

type CrearProductoParams struct {
	Nombre      string
	Precio      float64
	Stock       int64
	CategoriaID int64
}

func (q *Queries) CrearProducto(ctx context.Context, arg CrearProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, crearProducto,
		arg.Nombre,
		arg.Precio,
		arg.Stock,
		arg.CategoriaID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Precio,
		&i.Stock,
		&i.CategoriaID,
	)
	return i, err
}

const listarCategorias = `-- name: ListarCategorias :many
SELECT id, nombre, descripcion FROM categorias
`

// CATEGORIA
func (q *Queries) ListarCategorias(ctx context.Context) ([]Categoria, error) {
	rows, err := q.db.QueryContext(ctx, listarCategorias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categoria
	for rows.Next() {
		var i Categoria
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarProductos = `-- name: ListarProductos :many
SELECT id, nombre, precio, stock, categoria_id FROM productos
`

// PRODUCTO
func (q *Queries) ListarProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listarProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Precio,
			&i.Stock,
			&i.CategoriaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
